on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: ci

 jobs:
  kani:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Kani run
        uses: model-checking/kani-github-action@v0.13-alpha
        with:
          working-directory: quic/s2n-quic-core
          args: --tests
